<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>Dcs.RabbitMq.Common</RootNamespace>
    <AssemblyName>Dcs.RabbitMq.Common</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dcs.RabbitMq.Messaging\Dcs.RabbitMq.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" Version="3.2.56" />
  </ItemGroup>
</Project>